remote_theme: just-the-docs/just-the-docs
title: Agent Driven Development
description: A structured methodology for AI-assisted software development
show_downloads: true
github:
  repository_url: https://github.com/AgentDriven/Development
  zip_url: https://github.com/AgentDriven/Development/archive/refs/heads/main.zip
  tar_url: https://github.com/AgentDriven/Development/archive/refs/heads/main.tar.gz
  owner_url: https://github.com/AgentDriven
  owner_name: AgentDriven

# Color scheme
color_scheme: light

# Enable search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "AgentDriven on GitHub":
    - "https://github.com/AgentDriven/Development"

# Makes Aux links open in a new tab
aux_links_new_tab: true

# Navigation structure
nav:
  - title: Home
    url: /
  - title: Methodology
    url: /methodology.html
  - title: Phases
    url: /phases.html
  - title: Project Status
    url: /project.html
  - title: Development Journal
    url: /journal.html
  - title: Roadmap
    url: /plans/roadmap.html
  - title: .cursorrules
    url: /cursorrules.md 